<Project Sdk="Godot.NET.Sdk/4.6.3">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>NewGameProject</RootNamespace>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Fody" Version="6.9.3">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="MethodDecorator.Fody" Version="1.1.1" />
		<PackageReference Include="RogueSharp" Version="5.0.0-pre4" />
	</ItemGroup>
</Project>